ProjectMusic_BackEnd/ManagerMusic/Controllers/BuildSoftwareController.cs
using DataApplication.ApplicationUser.ApplicationBuildSoftware.BuildSoftwareUser;
using DataViewModel.ViewModelUser.BuildSoftware_Vm;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Threading.Tasks;

namespace ManagerMusic.Controllers
{
    public class BuildSoftwareController : Controller
    {
        private readonly IbuildSoftware_App context;
        public BuildSoftwareController(IbuildSoftware_App _context)
        {
            context = _context;
        }

        //page buildSoftware
        [HttpGet]
        public IActionResult PageBuildSoftware()
        {
            return View();
        }

        [HttpGet]
        public IActionResult JsonBuildSoftware()
        {
            var Stream = HttpContext.Request.Cookies["Token"];
            if (Stream != null)
            {
                var hander = new JwtSecurityTokenHandler();
                var jsontoken = hander.ReadToken(Stream);
                var token = jsontoken as JwtSecurityToken;
                // IdUser = Guid.Parse(token.Claims.FirstOrDefault(x => x.Type == "C_IdUser").Value);
                return new JsonResult(0);
            }
            else
            {
                return new JsonResult(1);
            }
        }

        //sent contribute user
        [HttpPost]
        public async Task<IActionResult> SentContributeUser(string Content)
        {
            var Stream = HttpContext.Request.Cookies["Token"];
            var hander = new JwtSecurityTokenHandler();
            var jsontoken = hander.ReadToken(Stream);
            var token = jsontoken as JwtSecurityToken;
            Guid IdUser = Guid.Parse(token.Claims.FirstOrDefault(x => x.Type == "C_IdUser").Value);

            var request = new SentContributeUser_V()
            {
                IdUser = IdUser,
                Content = Content,
                DateCreate = DateTime.UtcNow.AddHours(7)
            };
            var result = await context.SentContributeUser(request);
            return new JsonResult(result);
        }
    }
}

ProjectMusic_BackEnd/ManagerMusic/Controllers/HeaderMenuController.cs
using Microsoft.AspNetCore.Mvc;

namespace ManagerMusic.Controllers
{
    public class HeaderMenuController : Controller
    {
        //HeardMenu
        [HttpGet]
        public IActionResult Index()
        {
            return PartialView();
        }
    }
}

ProjectMusic_BackEnd/ManagerMusic/Controllers/ManagerDataController.cs
using DataApplication.ApplicationAdmin.ApplicationMusic.Music_App;
using DataViewModel.ViewModelAdmin.Music_Vm;
using ManagerMusic.Models.FileImage;
using ManagerMusic.Models.Paging.Page_Comment;
using ManagerMusic.Models.Paging.Page_HistoryUpdate;
using ManagerMusic.Models.Paging.Page_Rating;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Threading.Tasks;
using static DataUtilities.NameRoleSetting;

namespace ManagerMusic.Controllers
{
    [Authorize]
    public class ManagerDataController : BaseController
    {
        private readonly ILogger<ManagerDataController> _logger;
        private readonly ImusicApplication _Context;
        public ManagerDataController(ILogger<ManagerDataController> logger, ImusicApplication Context)
        {
            _logger = logger;
            _Context = Context;

        }

        //GetAll Music
        [Authorize(Roles = RoleSetting.symbolRole_Satff + "," + RoleSetting.symbolRole_Admin)]
        [HttpGet]
        public IActionResult IndexFile()
        {
            return View();
        }
        [Authorize(Roles = RoleSetting.symbolRole_Satff + "," + RoleSetting.symbolRole_Admin)]
        [HttpGet]
        public IActionResult Json_Music(int PageSize, int PageIndex, int IdSeason, 
                                        string SeachKey, int IdStatus, int Sort_No)
        {
            var Result = _Context.GetAllMusic(PageSize, PageIndex, IdSeason, SeachKey, IdStatus, Sort_No);
            return new JsonResult(Result);
        }

        //create Music
        [Authorize(Roles = RoleSetting.symbolRole_Satff + "," + RoleSetting.symbolRole_Admin)]
        [HttpGet]
        public IActionResult CreateMusic()
        {
            return View();
        }
        [Authorize(Roles = RoleSetting.symbolRole_Satff + "," + RoleSetting.symbolRole_Admin)]
        [HttpPost]
        public async Task<IActionResult> JsonCreateMusic(SaveFileMusic request)
        {
            var Stream = HttpContext.Request.Cookies["Token"];
            if (Stream == null)
            {
                var result_v = new NotificationMusic_V();
                result_v.IsStatus = 4;
                result_v.Status = false;
                return new JsonResult(result_v);
            }
            var hander = new JwtSecurityTokenHandler();
            var jsontoken = hander.ReadToken(Stream);
            var token = jsontoken as JwtSecurityToken;
            Guid IdUser = Guid.Parse(token.Claims.FirstOrDefault(x => x.Type == "C_IdUser").Value);
            CreateMusic_V result = JsonConvert.DeserializeObject<CreateMusic_V>(request.Music);
            //Split string name
            string[] NameImageString = request.fileImage.FileName.Split('.');
            result.DateCreate = DateTime.UtcNow.AddHours(7);
            result.TimeCreate = DateTime.UtcNow.AddHours(7);
            result.IdUser = IdUser;
            result.NoMusic = "BH" + DateTime.Now.Second + result.Year;
            result.FileMusic = request.fileDoc;
            result.FileName = request.fileDoc.FileName;
            result.TokenData = Stream;
            result.FileImage = request.fileImage;
            result.IdStaff = token.Claims.FirstOrDefault(x => x.Type == "C_IdStaff").Value;
            result.TypeImage = NameImageString[1];
            var result_Data = await _Context.CreateMusic(result);
            return new JsonResult(result_Data);
        }

        //Detail music
        [Authorize(Roles = RoleSetting.symbolRole_Satff + "," + RoleSetting.symbolRole_Admin)]
        [HttpGet]
        public IActionResult DetailMusic(Guid IdMusic)
        {
            ViewBag.IdMusic = IdMusic;
            return View();
        }
        [Authorize(Roles = RoleSetting.symbolRole_Satff + "," + RoleSetting.symbolRole_Admin)]
        [HttpPost]
        public async Task<IActionResult> JsonDetailMusic(Guid IdMusic)
        {
            var result = await _Context.DetailMusic(IdMusic);
            if(result == null)
            {
                return new JsonResult(0);
            }
            else
            {
                return new JsonResult(result);
            }
        }

        //get all comment by id music
        [Authorize(Roles = RoleSetting.symbolRole_Satff + "," + RoleSetting.symbolRole_Admin)]
        [HttpPost]
        public IActionResult JsonGetCommentByIdMusic(Guid IdMusic, int PageSize, int PageIndex)
        {
            var result =  _Context.GetAllCommentByIdMuisc(IdMusic);
            if(result.Count() == 0)
            {
                return new JsonResult(0);
            }
            else
            {
                var Result = result.Skip((PageIndex - 1) * PageSize).Take(PageSize);
                var PagingResult = new PagingComments()
                {
                    L_Comments = Result,
                    TotalComment = result.Count()
                };
                return new JsonResult(PagingResult);
            }
        }

        //get all rating by id muisc
        [Authorize(Roles = RoleSetting.symbolRole_Satff + "," + RoleSetting.symbolRole_Admin)]
        [HttpPost]
        public IActionResult JsonGetRatingByIdMusic(Guid IdMusic, int PageSize, int PageIndex)
        {
            var result = _Context.GetAllRatingByIdMuisc(IdMusic);
            if (result.Count() == 0)
            {
                return new JsonResult(0);
            }
            else
            {
                var Result = result.Skip((PageIndex - 1) * PageSize).Take(PageSize);
                var PagingResult = new PagingRatings()
                {
                    L_Ratings = Result,
                    TotalRatings = result.Count()
                };
                return new JsonResult(PagingResult);
            }
        }

        //Update Muisc
        [Authorize(Roles = RoleSetting.symbolRole_Admin + "," + RoleSetting.symbolRole_Satff)]
        [HttpGet]
        public IActionResult UpdateMusic(Guid IdMuisc)
        {
            ViewBag.IdMuiscUpdate = IdMuisc;
            return View();
        }
        [Authorize(Roles = RoleSetting.symbolRole_Satff + "," + RoleSetting.symbolRole_Admin)]
        [HttpPost]
        public async Task<IActionResult> JsonLoadUpdateMuisc(Guid IdMuisc)
        {
            if(IdMuisc == new Guid())
            {
                return new JsonResult(1); // null IdMuisc
            }
            else
            {
                var result = await _Context.GetUpdateMusic(IdMuisc);
                if(result == null)
                {
                    return new JsonResult(0); // null data
                }
                else
                {
                    return new JsonResult(result);
                }

            }
            
        }
        [Authorize(Roles = RoleSetting.symbolRole_Satff + "," + RoleSetting.symbolRole_Admin)]
        [HttpPost]
        public async Task<IActionResult> JsonUpdateMuisc(UpdateFileMuisc request)
        {
            UpdateMuisc_V result = JsonConvert.DeserializeObject<UpdateMuisc_V>(request.UpdateMuisc_V);
            if(result.IdMuisc == new Guid())
            {
                var result_E = new NotificationMusic_V()
                {
                    IsStatus = 5, // id music null
                    Status = false
                };
                return new JsonResult(result_E);
            }
            else
            {
                var Stream = HttpContext.Request.Cookies["Token"];
                var hander = new JwtSecurityTokenHandler();
                var jsontoken = hander.ReadToken(Stream);
                var token = jsontoken as JwtSecurityToken;
                Guid IdUser = Guid.Parse(token.Claims.FirstOrDefault(x => x.Type == "C_IdUser").Value);

                result.IdUser = IdUser;
                if (request.FileImage != null && request.FileMusic != null)
                {
                    //Split string name
                    string[] NameImageString = request.FileImage.FileName.Split('.');
                    result.NameFile = request.FileMusic.FileName;
                    result.FormFile_Muisc = request.FileMusic;
                    result.FormFile_Image = request.FileImage;
                    result.TypeImage = NameImageString[1];
                }
                result.TokenData = Stream;
                result.DateUpdate = DateTime.Now.AddHours(7);
                var result_S = await _Context.UpdateMuisc(result);
                return new JsonResult(result_S);
            }

        }

        //partial menu header for manager file
        [Authorize(Roles = RoleSetting.symbolRole_Satff + "," + RoleSetting.symbolRole_Admin)]
        [HttpGet]
        public IActionResult MenuManagerFile()
        {
            return View();
        }

        //get all status music
        [Authorize(Roles = RoleSetting.symbolRole_Satff + "," + RoleSetting.symbolRole_Admin)]
        [HttpGet]
        public IActionResult GetAllStatusMusic()
        {
            var result = _Context.GetAllSatusMusic();
            if(result.Count() == 0)
            {
                return new JsonResult(0);
            }
            else
            {
                return new JsonResult(result);
            }
        }

        //change status music
        [Authorize(Roles = RoleSetting.symbolRole_Satff + "," + RoleSetting.symbolRole_Admin)]
        [HttpPost]
        public async Task<IActionResult> ChangeStatusMusic(int IdStatus, Guid IdMusic)
        {
            var Stream = HttpContext.Request.Cookies["Token"];
            var hander = new JwtSecurityTokenHandler();
            var jsontoken = hander.ReadToken(Stream);
            var token = jsontoken as JwtSecurityToken;

ProjectMusic_BackEnd/ManagerMusic/Controllers/NotificationController.cs
using DataApplication.ApplicationUser.ApplicationNotification;
using ManagerMusic.Models.Paging.Page_Notification;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Threading.Tasks;

namespace ManagerMusic.Controllers
{
    [Authorize]
    public class NotificationController : BaseController
    {
        private readonly INotificationUser_App context;
        public NotificationController(INotificationUser_App _context)
        {
            context = _context;
        }

        //get Notification by id user
        [HttpGet]
        public IActionResult GetNotificationByUser(Guid IdUser, int take)
        {
            var result = context.GetNotificationByUser(IdUser, take);
            return new JsonResult(result);
        }

        //watched notification 
        [HttpGet]
        public async Task<IActionResult> WatchNotification(int IdNotification)
        {
            var result = await context.WatchedNotification(IdNotification);
            return new JsonResult(result);
        }

        //view all notification by id user
        [HttpGet]
        public IActionResult PageNotificationUer()
        {
            return View();
        }

        [HttpGet]
        public IActionResult GetAllNotificationByIdUser(int PageSize, int PageIndex)
        {
            var Stream = HttpContext.Request.Cookies["Token"];
            var hander = new JwtSecurityTokenHandler();
            var jsontoken = hander.ReadToken(Stream);
            var token = jsontoken as JwtSecurityToken;
            Guid IdUser = Guid.Parse(token.Claims.FirstOrDefault(x => x.Type == "C_IdUser").Value);
            var result = context.GetNotificationByUser(IdUser, 0);
            if (result.Count() == 0)
            {
                return new JsonResult(0);
            }
            else
            {
                var modalPaging = result.Skip((PageIndex - 1) * PageSize).Take(PageSize);
                var Result = new PagingNotification()
                {
                    L_Notification = modalPaging,
                    TotalNotification = result.Count()
                };
                return new JsonResult(Result);
            }
        }

        //delete notification user
        [HttpPost]
        public async Task<IActionResult> JsonDeleteNotification(List<int> Id, int IdNotification)
        {
            var result = await context.DeleteNotification(Id, IdNotification);
            return new JsonResult(result);
        }
    }
}

ProjectMusic_BackEnd/ManagerMusic/Views/HeaderMenu/Index.cshtml
@using ManagerMusic.Models
@inject LanguageService languade

<div class="az-header">
    <div class="container">
        <div class="az-header-left">
            <a asp-action="Index" asp-controller="Home" class="az-logo"><span></span> @languade.Getkey("Manager_Music")</a>
            <a asp-action="Index" asp-controller="Home" id="azMenuShow" class="az-header-menu-icon d-lg-none"><span></span></a>
        </div><!-- az-header-left -->
        <div class="az-header-menu">
            <div class="az-header-menu-header">
                <a asp-action="Index" asp-controller="Home" class="az-logo"><span></span> @languade.Getkey("Manager_Music")</a>
                <a href="" class="close">&times;</a>
            </div><!-- az-header-menu-header -->
            <ul class="nav">
                <li class="nav-item active show">
                    <a asp-action="Index" asp-controller="Home" class="nav-link">@languade.Getkey("Home_page")</a>
                </li>
                <li class="nav-item" id="ShowAndHide">
                    <a href="" class="nav-link with-sub">@languade.Getkey("System_page")</a>
                    <nav class="az-menu-sub">
                        <a asp-action="Login" asp-controller="Account" class="nav-link">@languade.Getkey("Login_page")</a>
                        <a asp-action="IndexRegiter" asp-controller="Account" class="nav-link">@languade.Getkey("Regiter_page")</a>
                    </nav>
                </li>
                <li class="nav-item">
                    <a asp-action="IndexListMusic" asp-controller="ClientListMusic" class="nav-link">@languade.Getkey("List_music")</a>
                </li>
                <li class="nav-item">
                    <a asp-action="PageBuildSoftware" asp-controller="BuildSoftware" class="nav-link">@languade.Getkey("build")</a>
                </li>
                <li class="nav-item">
                    <a href="" class="nav-link with-sub">@languade.Getkey("Language")</a>
                    <nav class="az-menu-sub">
                        <a asp-controller="Home" asp-action="ChangeLanguage" asp-route-culture="en" class="nav-link">@languade.Getkey("Language_en")</a>
                        <a asp-controller="Home" asp-action="ChangeLanguage" asp-route-culture="vi" class="nav-link">@languade.Getkey("Language_vi")</a>
                    </nav>
                </li>
            </ul>
        </div><!-- az-header-menu -->
        <div class="az-header-right">

            <div class="dropdown az-header-notification" id="modaldatashow">
                <a class="position-relative" style="margin-right: 20px;">
                    <i class="typcn typcn-bell"></i>
                    <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger" style="font-size: 10px; color: white;  z-index: 10; margin: -5px -10px;"></span>
                </a>
                <div class="dropdown-menu" style="width: 450px;">
                    <div class="az-dropdown-header mg-b-20 d-sm-none">
                        <a href="" class="az-header-arrow"><i class="icon ion-md-arrow-back"></i></a>
                    </div>
                    <h6 class="az-notification-title" style="text-align: center;">@languade.Getkey("Notifications")</h6>
                    <p class="az-notification-text"><b style="color: red;" id="NumberMessage"></b> @languade.Getkey("unread_message")</p>
                    <div class="az-notification-list" style="overflow: auto; height: 400px;" id="ShowListNotification"></div><!-- az-notification-list -->
                    <div class="dropdown-footer"><a asp-action="PageNotificationUer" asp-controller="Notification">@languade.Getkey("View_AllNotifications")</a></div>
                </div><!-- dropdown-menu -->
            </div><!-- az-header-notification -->
            <div class="dropdown az-profile-menu" id="modaldatashow">
                <a href="" class="az-img-user" id="AvataUserAdmin">
                    <i class="fas fa-user" style="font-size: 24px; margin: 2px 1px; color: #3b3939;"></i>
                </a>
                <div class="dropdown-menu">
                    <div class="az-dropdown-header d-sm-none">
                        <a href="" class="az-header-arrow"><i class="icon ion-md-arrow-back"></i></a>
                    </div>

                    <!-- info admin -->
                    <div class="az-header-profile">
                        <div class="az-img-user" id="ImageBig">                             
                             
                        </div><!-- az-img-user -->
                        <h6 id="TxtName" style="text-align:center;"></h6>
                        <span id="TxtRole"></span>
                    </div><!-- az-header-profile -->

                    <button type="button" id="btn_ShowInfoAdmin" class="dropdown-item"><i class="typcn typcn-user-outline"></i> @languade.Getkey("My_information")</button>
                    <a class="dropdown-item" disabled><i class="typcn typcn-edit"></i> @languade.Getkey("Edit_infomation")</a>
                    <a id="IndexFile_Heard" asp-action="IndexFile" asp-controller="ManagerData" class="dropdown-item"><i class="fas fa-cog"></i> @languade.Getkey("System_Management")</a>
                    <a id="LogOut" asp-action="LogOut" asp-controller="Account" class="dropdown-item"><i class="typcn typcn-power-outline"></i> @languade.Getkey("Logout")</a>

                </div><!-- dropdown-menu -->
            </div>
        </div><!-- az-header-right -->
    </div><!-- container -->
</div><!-- az-header -->
<!-- Modal Show Infomation Admin -->
<div class="modal showmodal-seachNamemusic" tabindex="-1" id="modal_ShowInfomationAdmin">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">@languade.Getkey("Login_Information")</h5>
                <button type="button" class="btn-close" id="btn_CloseModalInfoAdmin">X</button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label class="form-label">@languade.Getkey("FirstandLast_Name")</label>
                    <input type="text" class="form-control" disabled id="TxtNames">
                </div>
                <div class="mb-3">
                    <label class="form-label">Email</label>
                    <input type="text" class="form-control" disabled id="TxtGmail">
                </div>
                <div class="mb-3">
                    <label class="form-label">@languade.Getkey("Birthday")</label>
                    <input type="text" class="form-control" disabled id="TxtBirthday">
                </div>
                <div class="mb-3">
                    <label class="form-label">@languade.Getkey("Role_App")</label>
                    <input type="text" class="form-control" disabled id="TxtRoleName">
                </div>
                <div class="mb-3">
                    <label class="form-label">@languade.Getkey("RegiterDate")</label>
                    <input type="text" class="form-control" disabled id="TxtDateRegiter">
                </div>
            </div>
            <div class="modal-footer">
                @*<a href="#" class="btn btn-primary" disabled><i class="fas fa-edit"></i> Chỉnh Sửa Thông Tin</a>*@
            </div>
        </div>
    </div>
</div>

<input type="hidden" value="@languade.Getkey("User")" id="v_uer" />
<input type="hidden" value="@languade.Getkey("Staff")" id="v_staff" />
<input type="hidden" value="@languade.Getkey("Admin")" id="v_admin" />
<input type="hidden" value="@languade.Getkey("read_Error")" id="read_Error"/>
<input type="hidden" value="@languade.Getkey("read_Success")" id="read_Success"/>
<input type="hidden" value="@languade.Getkey("Notification_Error")" id="Notification_Error"/>
<input type="hidden" value="@languade.Getkey("Nofitication_Success")" id="Nofitication_Success"/>
<input type="hidden" value="@languade.Getkey("not_seen")" id="not_seen"/>
<input type="hidden" value="@languade.Getkey("watched")" id="watched"/>