ProjectMusic_BackEnd/ManagerMusic/Models/Paging/Page_Plans/Pading_NotificationPlans.cs
using DataViewModel.ViewModelAdmin.Plan_Vm;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ManagerMusic.Models.Paging.Page_Plans
{
    public class Pading_NotificationPlans
    {
        public IEnumerable<GetAllNotificationPlan_V> L_NotificationPlan { get; set; }
        public int TotalNotification { get; set; }
    }
}

ProjectMusic_BackEnd/ManagerMusic/Models/Paging/Page_Plans/Pading_Plan.cs
using DataViewModel.ViewModelAdmin.Plan_Vm;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ManagerMusic.Models.Paging.Page_Plans
{
    public class Pading_Plan
    {
        public int TotalPlan { get; set; }
        public string NameRole { get; set; }
        public List<List_getAllPlans_V> L_Plans { get; set; } = new List<List_getAllPlans_V>();
    }
}

ProjectMusic_BackEnd/ManagerMusic/Models/Paging/Page_Plans/Pading_UserRolePlan.cs
using DataViewModel.ViewModelAdmin.Plan_Vm;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ManagerMusic.Models.Paging.Page_Plans
{
    public class Pading_UserRolePlan
    {
        public IEnumerable<GetAllUserRolePlan_V> L_UserRolePlan { get; set; }
        public int TotalUser { get; set; }
    }
}

ProjectMusic_BackEnd/ManagerMusic/Controllers/ManagerPlansController.cs
using DataApplication.ApplicationAdmin.ApplicationPlans.Plan_app;
using DataApplication.ApplicationAdmin.ApplicationStaff.Staff_App;
using DataViewModel.ViewModelAdmin.Plan_Vm;
using ManagerMusic.Models.Paging.Page_Plans;
using ManagerMusic.Models.Plans;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Threading.Tasks;
using static DataUtilities.NameRoleSetting;
using DataViewModel.ViewModelAdmin.ConverFile_Vm;
using Newtonsoft.Json;

namespace ManagerMusic.Controllers
{
    [Authorize]
    public class ManagerPlansController : Controller
    {
        private readonly Iplan_App Context;
        private readonly Istaff_app context_Staff;
        public ManagerPlansController(Iplan_App _Context, Istaff_app _context_Staff)
        {
            Context = _Context;
            context_Staff = _context_Staff;
        }

        //get all plans by Role 
        [Authorize(Roles = RoleSetting.symbolRole_Admin + "," + RoleSetting.symbolRole_Satff)]
        [HttpGet]
        public IActionResult Page_Plans()
        {
            L_PlanFileUpdate = new List<CreatePlanFile_V>();
            ViewBag.IdUser = GetGuidCurrentUserLogin();
            return View();
        }

        [Authorize(Roles = RoleSetting.symbolRole_Admin + "," + RoleSetting.symbolRole_Satff)]
        [HttpGet]
        public async Task<IActionResult> GetAllPlansByIdUser(Guid IdUser, int PageIndex, 
                                                             int PageSize, string DateCreate, 
                                                             string DateCompelete, int IdStatus)
        {
            var result_Data = new GetAllPlans_V();
            result_Data = await Context.GetAllPlanByIdUser(IdUser);
            List<List_getAllPlans_V> L_PlanPading = new List<List_getAllPlans_V>();
            if(IdStatus != 0)
            {
                var L_PlanStatus = result_Data.L_Plans.Where(x => x.IdStatus == IdStatus).ToList();
                L_PlanPading = L_PlanStatus.OrderByDescending(x => x.IdPlan)
                                    .Skip((PageIndex - 1) * PageSize).Take(PageSize).ToList();
            }
            else
            {
                if (DateCreate != null)
                {
                    string[] StrDate = DateCreate.Split(" to ");
                    DateTime DateTime_1 = Convert.ToDateTime(StrDate[0]);
                    DateTime DateTime_2 = Convert.ToDateTime(StrDate[1]);
                    var L_DateCreate = result_Data.L_Plans.Where(x => x.DateCreatePlan.Date >= DateTime_1 && x.DateCreatePlan.Date <= DateTime_2).ToList();
                    L_PlanPading = L_DateCreate.OrderByDescending(x => x.IdPlan)
                                    .Skip((PageIndex - 1) * PageSize).Take(PageSize).ToList();
                }
                else if (DateCompelete != null)
                {
                    string[] StrDate = DateCompelete.Split(" to ");
                    DateTime DateTime_1 = Convert.ToDateTime(StrDate[0]);
                    DateTime DateTime_2 = Convert.ToDateTime(StrDate[1]);
                    var L_DateCompelete = result_Data.L_Plans.Where(x => x.DateComplete.Date >= DateTime_1 && x.DateComplete.Date <= DateTime_2).ToList();
                    L_PlanPading = L_DateCompelete.OrderByDescending(x => x.IdPlan)
                                    .Skip((PageIndex - 1) * PageSize).Take(PageSize).ToList();
                }
                else
                {
                    L_PlanPading = result_Data.L_Plans.OrderByDescending(x => x.IdPlan)
                                    .Skip((PageIndex - 1) * PageSize).Take(PageSize).ToList();
                }
            }
            
            var Result = new Pading_Plan()
            {
                TotalPlan = result_Data.L_Plans.Count(),
                L_Plans = L_PlanPading,
                NameRole = result_Data.NameRole
            };
            return new JsonResult(Result);
        }

        //take plan by id user
        [Authorize(Roles = RoleSetting.symbolRole_Admin + "," + RoleSetting.symbolRole_Satff)]
        [HttpPost]
        public async Task<IActionResult> TakePlansByIdUser(int IdPlan)
        {
            var result = new NotificationPlans_V();
            Guid IdUser = GetGuidCurrentUserLogin();
            result = await Context.TakePlanByIdUser(IdUser, IdPlan);
            return new JsonResult(result);
        }

        //page detail plan by id user
        [Authorize(Roles = RoleSetting.symbolRole_Admin + "," + RoleSetting.symbolRole_Satff)]
        [HttpGet]
        public IActionResult Page_DetailPlan(int IdPlan)
        {
            ViewBag.IdPlan = IdPlan;
            return View();
        }

        //detail plan by id user
        [Authorize(Roles = RoleSetting.symbolRole_Admin + "," + RoleSetting.symbolRole_Satff)]
        [HttpGet]
        public async Task<IActionResult> DetailPlanByIdUser(int IdPlan)
        {
            var result = new GetAllPlans_V();         
            Guid IdUser = GetGuidCurrentUserLogin();
            result = await Context.DetailPlanById(IdUser, IdPlan);
            return new JsonResult(result);
        }

        //cancel plan by id user
        [Authorize(Roles = RoleSetting.symbolRole_Admin + "," + RoleSetting.symbolRole_Satff)]
        [HttpPost]
        public async Task<IActionResult> CancelPLanByIdUser(int IdPlan, string Content)
        {
            var result = new NotificationPlans_V();
            Guid IdUser = GetGuidCurrentUserLogin();
            result = await Context.CancelPlanByIdUser(IdUser, IdPlan, Content);
            return new JsonResult(result);
        }

        //get amount notification plans
        [Authorize(Roles = RoleSetting.symbolRole_Admin)]
        [HttpGet]
        public IActionResult AmountNotificationPlans()
        {
            Guid IdUser = GetGuidCurrentUserLogin();
            var result = Context.AmountNotificationPlans(IdUser);
            return new JsonResult(result);
        }

        //Update Plan by Admin
        [Authorize(Roles = RoleSetting.symbolRole_Admin)]
        [HttpGet]
        public async Task<IActionResult> UpdatePlanAdmin_Get(int IdPlan)
        {
            Guid IdUser = GetGuidCurrentUserLogin();
            var result = await Context.UpdatePlanByAdmin_Get(IdPlan, IdUser);
            return new JsonResult(result);
        }

        [Authorize(Roles = RoleSetting.symbolRole_Admin)]
        [HttpPost]
        public async Task<IActionResult> UpdatePlanAdmin_Post(int IdPlan, string TitlePlan, string ContentPlan)
        {
            var Result_Json = new NotificationPlans_V();
            Guid IdUser = GetGuidCurrentUserLogin();

            var result = new UpdatePlan_V();
            result.IdPlan = IdPlan;
            result.NamePlan = TitlePlan;
            result.ContentPlan = ContentPlan;
            if(L_PlanFileUpdate.Count() != 0)
            {
                result.L_FilePlans = L_PlanFileUpdate;
            }
            Result_Json = await Context.UpdatePlanByAdmin_Post(result, IdUser);
            return new JsonResult(Result_Json);
        }


        //Update File Plan by Admin
        private static List<CreatePlanFile_V> L_PlanFileUpdate = new List<CreatePlanFile_V>();
        [Authorize(Roles = RoleSetting.symbolRole_Admin)]
        [HttpPost]
        public async Task<IActionResult> UpdateFile_Plan(UpdateFile_Plan request)
        {
            var IpFile = JsonConvert.DeserializeObject<IdPlan>(request.IdPlan_Json);
            var FileName = request.FileUpdate.FileName;
            string[] StrSlip = FileName.Split('.');
            var ConverFile = new ConverFile();
            var result = new CreatePlanFile_V();
            result.NameFile = FileName;
            result.TypeFile = StrSlip[1];
            result.Id = IpFile.Id;
            result.DateCreate = DateTime.UtcNow.AddHours(7);
            result.DateCreate_Str = result.DateCreate.ToString("dd/MM/yyyy");
            switch (StrSlip[1])
            {
                case "pdf":
                    ConverFile = await context_Staff.ConverDataFile(request.FileUpdate);                  
                    result.MimeType = ConverFile.MineType;
                    result.ContentFile = ConverFile.ContentFile;
                    break;
                case "docx":
                    ConverFile = await context_Staff.ConverDataFile(request.FileUpdate);
                    result.MimeType = ConverFile.MineType;
                    result.ContentFile = ConverFile.ContentFile;
                    break;
                case "xlsx":
                    ConverFile = await context_Staff.ConverDataFile(request.FileUpdate);
                    result.MimeType = ConverFile.MineType;
                    result.ContentFile = ConverFile.ContentFile;
                    break;
                default:
                    return new JsonResult(result.Id = 0);
            }
            L_PlanFileUpdate.Add(result);
            return new JsonResult(result);
        }

        [Authorize(Roles = RoleSetting.symbolRole_Admin)]
        [HttpPost]
        public IActionResult CloseUpdateFile_Plan()
        {
            L_PlanFileUpdate = new List<CreatePlanFile_V>();
            return new JsonResult(true);
        }

        //Update Date and Time plan by Admin
        [Authorize(Roles = RoleSetting.symbolRole_Admin)]
        [HttpPost]
        public async Task<IActionResult> UpdateDateTimePlan(DateTime DateRequest, TimeSpan TimeRequest, int IdPlan)
        {
            var Result_Json = new NotificationPlans_V();
            Guid IdUser = GetGuidCurrentUserLogin();
            Result_Json = await Context.UpdateDateTimePlanByAdmin(DateRequest, TimeRequest, IdPlan, IdUser);
            return new JsonResult(Result_Json);
        }

        //get all staff for role plan

ProjectMusic_BackEnd/ManagerMusic/Views/ManagerPlans/Page_Plans.cshtml
@using ManagerMusic.Models
@inject LanguageService languade
@{
    ViewData["Title"] = languade.Getkey("Task_Manager");
    Layout = "~/Views/Shared/Manager_Plans/ManagerPlans.cshtml";
}

<div class="az-content-body pd-lg-l-40 d-flex flex-column">
    <div class="az-content-breadcrumb">
        <span><a asp-action="Index" asp-controller="Home" style="color: #97a3b9;">@languade.Getkey("Home_page")</a></span>
        <span><a href="#" style="color: #97a3b9;">@languade.Getkey("Admin_Information")</a></span>
        <span>@languade.Getkey("Task_Manager")</span>
    </div>

    <h2 class="az-content-title">@languade.Getkey("Task_Manager")</h2>
    <div class="row">
        <div class="col-md-12">
            <p style="text-align:right;">

                <a id="TotalCancelPlans" asp-action="Page_PlansCancel" asp-controller="ManagerPlans" style="border: none;" class="btn btn-outline-secondary" data-bs-toggle="tooltip" data-bs-placement="top" title="@languade.Getkey("Totaltask_canceled")">
                    <i class="fas fa-bell"></i>
                    <span style="color: red; font-weight: 600;" id="TotalNotificationPlan"></span>
                </a>

                <a id="Btn_FulterDate" style="border: none;" class="btn btn-outline-secondary" data-bs-toggle="tooltip" data-bs-placement="top" title="@languade.Getkey("Findtasks_date")"><i class="far fa-calendar-times"></i></a>

                <a id="Btn_SelectStatus" style="border: none;" class="btn btn-outline-secondary" data-bs-toggle="tooltip" data-bs-placement="top" title="@languade.Getkey("Choose_Status")"><i class="fas fa-list"></i></a>

                <a asp-action="Page_Plans" asp-controller="ManagerPlans" style="border: none;" class="btn btn-outline-secondary" data-bs-toggle="tooltip" data-bs-placement="top" title="@languade.Getkey("reset")"><i class="fas fa-power-off"></i></a>

                <a style="border: none;" class="btn btn-outline-secondary">@languade.Getkey("Total_Task") <b id="TxtTotalPlan"></b></a>

            </p>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">@languade.Getkey("No") <i class="fa fa-fw fa-sort"></i></th>
                        <th scope="col" style="text-align: center;">@languade.Getkey("Task")</th>
                        <th scope="col" style="text-align: center;">@languade.Getkey("Performers")</th>
                        <th scope="col" style="text-align: center;">@languade.Getkey("Admin_Request")</th>
                        <th scope="col" style="text-align: center;">@languade.Getkey("datecreate")</th>
                        <th scope="col" style="text-align: center;">@languade.Getkey("Expirationdate_time")</th>
                        <th scope="col" style="text-align: center;">@languade.Getkey("Status")</th>
                        <th scope="col" style="text-align: center;">@languade.Getkey("Work_Progress")</th>
                        <th scope="col" style="text-align: center;">@languade.Getkey("Options")</th>
                    </tr>
                </thead>
                <tbody id="Body_Data">
                </tbody>
            </table>
            <p style="text-align:right;">@languade.Getkey("page") : <b id="ItemInPage" style="color:red;"></b>/<b id="TotalItem" style="color:black;"></b></p>
            <!-- Pagination -->
            <div class="row" style="clear: both;">
                <div id="pagination" class="pagination"></div>
            </div>

        </div>
    </div>

    <div class="az-footer mg-t-auto">
        <div class="container">
            <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">@languade.Getkey("Design_In_2022")</span>
            <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Do <a href="#" target="_blank">@languade.Getkey("Petros_Tuong")</a> from duytuong0503@gmail.com</span>
        </div><!-- container -->
    </div><!-- az-footer -->
</div><!-- az-content-body -->
<!-- choose option activer funtion file -->
<div class="modal showmodal-seachNamemusic" tabindex="-1" id="modal_ShowPlan">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><i class="fas fa-toolbox"></i> @languade.Getkey("Requested_ask")</h5>
                <button type="button" class="btn-close" id="btn_closePlan">X</button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <p style="text-align:center;">
                            <button type="button" class="btn btn-outline-danger" id="btn_TakePlan">@languade.Getkey("agree")</button>
                        </p>
                    </div>
                    <div class="col-md-6">
                        <p style="text-align:center;">
                            <button type="button" class="btn btn-outline-primary" id="btn_CancelPlan">@languade.Getkey("cancel")</button>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- choose option activer funtion file -->
<div class="modal showmodal-seachNamemusic" tabindex="-1" id="modal_ShowCancelPlan">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">@languade.Getkey("AreYouSure_CancelTask")</h5>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <p style="text-align:center;">
                            <button type="button" class="btn btn-outline-danger" id="btn_1CancelPlan">@languade.Getkey("agree")</button>
                        </p>
                    </div>
                    <div class="col-md-6">
                        <p style="text-align:center;">
                            <button type="button" class="btn btn-outline-primary" id="btn_2CancelPlan">@languade.Getkey("cancel")</button>
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <textarea id="ContentTxt" class="form-control" placeholder="@languade.Getkey("Enterreason_task")"></textarea>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal loading create saint -->
<div class="modal showmodal-seachNamemusic" tabindex="-1" id="modal_LoadingCreateMusic">
    <div class="modal-dialog">
        <div class="modal-content" style="background:none; border:none;">
            <div class="modal-body">
                <div class="row" style="margin-top:200px;">
                    <div class="col-md-4"></div>
                    <div class="col-md-4">
                        <div class="spinner-grow text-primary" role="status">
                            <span class="visually-hidden"></span>
                        </div>
                        <div class="spinner-grow text-secondary" role="status">
                            <span class="visually-hidden"></span>
                        </div>
                        <div class="spinner-grow text-success" role="status">
                            <span class="visually-hidden"></span>
                        </div>
                    </div>
                    <div class="col-md-4"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--Modal fuliter plan by date-->
<div class="modal showmodal-seachNamemusic" tabindex="-1" id="modal_FuliterDate">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">@languade.Getkey("FilterDate_List")</h5>
                <button type="button" class="btn-close" id="BtnCloseFulter">X</button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <p style="font-size: 17px; font-family: initial;">
                            @languade.Getkey("Select_Dates")
                        </p>
                        <input style="margin: 10px 0px; font-size: 16px; font-weight: 600; width: 100%; font-family: initial;" type="text" id="rangeDate" placeholder="@languade.Getkey("select_date")" data-input>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button id="Btn_FuilterDateCompelete" type="button" style="border-radius: 10px;" class="btn btn-primary">@languade.Getkey("Expiration_date")</button>
                <button id="Btn_FuilterDateTime" style="border-radius: 10px;" type="button" class="btn btn-primary">@languade.Getkey("datecreate")</button>
            </div>
        </div>
    </div>
</div>

<!--Modal select status plan-->
<div class="modal showmodal-seachNamemusic" tabindex="-1" id="modal_SelectStatusPlan">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><i class="far fa-caret-square-down"></i> @languade.Getkey("SelectTask_Status")</h5>
                <button type="button" class="btn-close" id="Btn_CloseSelectStatus">X</button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <select class="form-control" id="Select_Status" style="border-radius: 10px;">
                    </select>
                </div>
            </div>
            <div class="modal-footer">
                <button id="Btn_SeachStatus" type="button" class="btn btn-primary"><i class="fas fa-search"></i> @languade.Getkey("Seach")</button>
            </div>
        </div>
    </div>
</div>

<input type="hidden" value="@ViewBag.IdUser" id="IdUser" />
<input type="hidden" value="@languade.Getkey("head")" id="head" />
<input type="hidden" value="@languade.Getkey("next")" id="next" />
<input type="hidden" value="@languade.Getkey("last")" id="last" />
<input type="hidden" value="@languade.Getkey("Before")" id="Before" />
<input type="hidden" value="@languade.Getkey("NotFindStaff")" id="NotFindStaff" />
<input type="hidden" value="@languade.Getkey("Notification_Error")" id="Notification_Error"/>
<input type="hidden" value="@languade.Getkey("Nofitication_Success")" id="Nofitication_Success" />
<input type="hidden" value="@languade.Getkey("Notaskfound_employee")" id="Notaskfound_employee"/>
<input type="hidden" value="@languade.Getkey("EXPIRED")" id="EXPIRED"/>
<input type="hidden" value="@languade.Getkey("not_received")" id="not_received"/>
<input type="hidden" value="@languade.Getkey("Received")" id="Received"/>
<input type="hidden" value="@languade.Getkey("Cancelled")" id="Cancelled"/>
<input type="hidden" value="@languade.Getkey("View_task")" id="View_task"/>
<input type="hidden" value="@languade.Getkey("Clear_task")" id="Clear_task"/>
<input type="hidden" value="@languade.Getkey("Taking_mission")" id="Taking_mission"/>
<input type="hidden" value="@languade.Getkey("Cancel_task")" id="Cancel_task"/>
<input type="hidden" value="@languade.Getkey("passed_match")" id="passed_match"/>
<input type="hidden" value="@languade.Getkey("Notaskwith_codefound")" id="Notaskwith_codefound"/>
<input type="hidden" value="@languade.Getkey("Successfultask_received")" id="Successfultask_received"/>
<input type="hidden" value="@languade.Getkey("EmployeeCode_Invalid")" id="EmployeeCode_Invalid"/>
<input type="hidden" value="@languade.Getkey("Pleaseenter_accepttask")" id="Pleaseenter_accepttask"/>
<input type="hidden" value="@languade.Getkey("Failedaccepttask_successfully")" id="Failedaccepttask_successfully"/>
<input type="hidden" value="@languade.Getkey("Choose_Status")" id="Choose_Status"/>
<input type="hidden" value="@languade.Getkey("Cleartask_successfully")" id="Cleartask_successfully"/>

ProjectMusic_BackEnd/ManagerMusic/Views/ManagerPlans/Page_PlansCancel.cshtml
@using ManagerMusic.Models
@inject LanguageService languade
@{
    ViewData["Title"] = languade.Getkey("TaskManager_denied");
    Layout = "~/Views/Shared/Manager_Plans/ManagerCancelPlans.cshtml";
}

<div class="az-content-body pd-lg-l-40 d-flex flex-column">
    <div class="az-content-breadcrumb">
        <span><a asp-action="Index" asp-controller="Home" style="color: #97a3b9;">@languade.Getkey("Home_page")</a></span>
        <span><a href="#" style="color: #97a3b9;">@languade.Getkey("Admin_Information")</a></span>
        <span><a asp-controller="ManagerPlans" asp-action="Page_Plans" style="color: #97a3b9;">@languade.Getkey("Task_Manager")</a></span>
        <span>@languade.Getkey("TaskManager_denied")</span>
    </div>

    <h2 class="az-content-title">@languade.Getkey("TaskManager_denied")</h2>
    <div class="row">
        <div class="col-md-12">
            <p style="text-align:right;">

                <a asp-action="Page_PlansCancel" asp-controller="ManagerPlans" style="border: none;" class="btn btn-outline-secondary" data-bs-toggle="tooltip" data-bs-placement="top" title="@languade.Getkey("reset")"><i class="fas fa-power-off"></i></a>

                <a style="border: none;" class="btn btn-outline-secondary">@languade.Getkey("Total_Task"): <b id="TxtTotalPlan"></b></a>

            </p>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col">@languade.Getkey("No") <i class="fa fa-fw fa-sort"></i></th>
                        <th scope="col" style="text-align: center;">@languade.Getkey("Task_Code")</th>
                        <th scope="col" style="text-align: center;">@languade.Getkey("Performers")</th>
                        <th scope="col" style="text-align: center;">@languade.Getkey("Admin_Request")</th>
                        <th scope="col" style="text-align: center;">@languade.Getkey("datecreate")</th>
                        <th scope="col" style="text-align: center;">@languade.Getkey("Content")</th>
                    </tr>
                </thead>
                <tbody id="Body_Data">
                </tbody>
            </table>
            <p style="text-align:right;">@languade.Getkey("page") : <b id="ItemInPage" style="color:red;"></b>/<b id="TotalItem" style="color:black;"></b></p>
            <!-- Pagination -->
            <div class="row" style="clear: both;">
                <div id="pagination" class="pagination"></div>
            </div>

        </div>
    </div>

    <div class="az-footer mg-t-auto">
        <div class="container">
            <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">@languade.Getkey("Design_In_2022")</span>
            <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Do <a href="#" target="_blank">@languade.Getkey("Petros_Tuong")</a> from duytuong0503@gmail.com</span>
        </div><!-- container -->
    </div><!-- az-footer -->
</div><!-- az-content-body -->

<input type="hidden" value="@languade.Getkey("head")" id="head" />
<input type="hidden" value="@languade.Getkey("next")" id="next" />
<input type="hidden" value="@languade.Getkey("last")" id="last" />
<input type="hidden" value="@languade.Getkey("Before")" id="Before" />